import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Newsletter from "./Components/Newsletter";

const inter = Playfair_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create2  Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-100">
      <body className={inter.className} >


        <nav className="bg-gray-100 border-gray-200 sticky z-[999] top-[0px]">
          <div className="container flex flex-wrap items-center justify-between mx-auto p-4">
            <a href="https://flowbite.com/" className="flex items-center  rtl:space-x-reverse font-italic text-italic text-3xl font-bold italic  text-siteDefaultColor">
             Raj.
            </a>
            <button data-collapse-toggle="navbar-default" type="button" className="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 " aria-controls="navbar-default" aria-expanded="false">
              <span className="sr-only">Open main menu</span>
            </button>
            <div className="hidden w-full md:block md:w-auto" id="navbar-default">
              <ul className="font-medium text-[18px] flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-100 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 bg-transparent  ">
             
                <li>
                  <a href="#" className="block py-2 px-3 text-gray-700 hover:bg-gray-100 border-b-2 border-transparent hover:border-siteDefaultColor hover:text-siteDefaultColor ">About</a>
                </li>
                <li>
                  <a href="#" className="block py-2 px-3 text-gray-700 hover:bg-gray-100 border-b-2 border-transparent hover:border-siteDefaultColor hover:text-siteDefaultColor ">Learn</a>
                </li>
                <li>
                  <a href="#" className="block py-2 px-3 text-gray-700 hover:bg-gray-100 border-b-2 border-transparent hover:border-siteDefaultColor hover:text-siteDefaultColor ">Open Source</a>
                </li>
                <li>
                  <a href="#" className="block py-2 px-3 text-gray-700 hover:bg-gray-100 border-b-2 border-transparent hover:border-siteDefaultColor hover:text-siteDefaultColor ">Writings</a>
                </li>
                <li>
                  <a href="#" className="block py-2 px-3 text-gray-700 hover:bg-gray-100 border-b-2 border-transparent hover:border-siteDefaultColor hover:text-siteDefaultColor ">Projects</a>
                </li>
                <li>
                  <a href="#" className="block py-2 px-3  text-white bg-siteDefaultColor rounded-full pl-4 pr-4 border border-b-1 hover:border hover:border-b-1 hover:border-siteDefaultColor hover:bg-white hover:text-siteDefaultColor">Contact Me</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        {children}
        <Newsletter />
        <div className="bg-white w-full text-center pb-14">
        <a href="https://www.linkedin.com/in/iamrajneesh/" className="text-2xl font-medium underline text-black">Follow on Linkedin</a>
        </div>
      
      </body>
    </html>
  );
}
